# Generated by Django 5.2.17 on 2026-09-30 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default='Stone Fort', max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('time_zone', models.CharField(default='America/New_York', max_length=64)),
                ('capacity', models.PositiveSmallIntegerField(default=8, help_text='Total people, including the host')),
                ('join_policy', models.CharField(choices=[('request', 'Host approval'), ('open', 'Open until full')], default='request', max_length=16)),
                ('private_meetup', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_outings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('waitlisted', 'Waitlisted')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outing_participations', to=settings.AUTH_USER_MODEL)),
                ('outing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='community.outing')),
            ],
        ),
        migrations.AddConstraint(
            model_name='outing',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='outing_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='outing',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='outing_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('outing', 'member'), name='one_participation_per_member'),
        ),
    ]
