# Generated by Django 5.2.17 on 2026-10-01 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_discussion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='community.discussionpost')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='community.discussionreply')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discussion_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_discussion_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dismiss', 'Report dismissed'), ('hide_post', 'Post hidden'), ('hide_reply', 'Reply hidden'), ('restore_post', 'Post restored'), ('restore_reply', 'Reply restored'), ('suspend', 'Posting suspended'), ('restore_member', 'Posting restored')], max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.discussionpost')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='community.discussionreply')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='community.discussionreport')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PostingSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_suspended', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='posting_suspension', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='discussionreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('post__isnull', False), ('reply__isnull', True)), models.Q(('post__isnull', True), ('reply__isnull', False)), _connector='OR'), name='discussion_report_one_target'),
        ),
        migrations.AddConstraint(
            model_name='discussionreport',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('reporter', 'post'), name='one_report_per_member_post'),
        ),
        migrations.AddConstraint(
            model_name='discussionreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reply__isnull', False)), fields=('reporter', 'reply'), name='one_report_per_member_reply'),
        ),
    ]
