from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
issues = [
('Confirm the pilot sector and local community needs', 'M0 Data feasibility', 'P0', [],
 'Choose a small first area that people can maintain, and test whether joinable climbing sessions solve the local problem.',
 ['Interview five to eight local climbers, including people who are new to Chattanooga.', 'Choose one Stone Fort sector and identify two potential field reviewers.', 'Identify the exact climbing area meant by St. Elmo before publishing it.', 'Record the first supported grade ranges, session scenarios, and proposed success measures.', 'Confirm the Crag Conditions URL with its owner; the supplied candidate page describes UK coverage.'],
 ['A written scope names the pilot sector and community workflows.', 'Interview findings distinguish real needs from assumptions.', 'A person accepts responsibility for catalog corrections and community moderation.']),
('Audit data rights and assemble a reviewed pilot catalog', 'M0 Data feasibility', 'P0', [1],
 'Establish a legal and maintainable source of useful climb facts before building route recommendations.',
 ['Audit a sample of current OpenBeta coverage and retain field-level provenance.', 'Complete the source register, including storage, display, model processing, map derivatives, and export rights.', 'Document permission requirements for any supplied PDFs; keep restricted originals private.', 'Collect original observations where permitted sources are incomplete.', 'Review 30 to 60 candidate climbs with stable IDs, discipline-specific grades, aliases, and uncertainty.', 'Define import dry runs, duplicate resolution, revisions, withdrawal, and cache invalidation.'],
 ['Every published field has approved provenance and permitted intended uses.', 'No Mountain Project scrape, unlicensed PDF content, or restricted photos enter the repository.', 'The pack contains relevant warmups and projects for the pilot group.', 'Unknown coordinates and disputed grades remain explicit rather than guessed.']),
('Scaffold the application and prove Docker deployment and restoration', 'M1 Community foundation', 'P0', [],
 'Create the smallest reproducible application on the existing VPS, with a recovery procedure that has been exercised.',
 ['Confirm stack choice, VPS resources, operating system, domain, reverse proxy, and backup destination.', 'Add Django and PostgreSQL with locked dependencies, Dockerfile, compose.yaml, and placeholder-only .env.example.', 'Configure health checks, private database networking, TLS integration, secure sessions, and production settings.', 'Add actual development, test, and migration commands to README and AGENTS.md.', 'Add CI for the application and configure private vulnerability reporting.', 'Document updates, controlled migrations, encrypted off-host backups, and rollback.', 'Restore a backup into an isolated instance and measure recovery.'],
 ['A clean checkout starts with documented commands and no embedded secrets.', 'Only intended proxy ports are publicly reachable.', 'Database and approved media survive container replacement.', 'An isolated restore recovers representative records and media.']),
('Build pseudonymous profiles and joinable climbing outings', 'M1 Community foundation', 'P0', [3],
 'Help a climber with few local connections find and join an outing with clear expectations.',
 ['Implement lightweight accounts, password recovery design, and pseudonymous profiles without identity or skill verification.', 'Separate comfortable and project grades by discipline and permit optional availability and interests.', 'Create area-filtered and date-filtered outing cards with capacity, join policy, meeting visibility, and time zone.', 'Implement requested, accepted, declined, withdrawn, and waitlisted participation states.', 'Support edits, cancellation, and in-app notifications for accepted participants.', 'Default precise meetup details and participant lists to accepted participants.', 'Test private-plan authorization and concurrent capacity updates.'],
 ['A new member can find an outing, request to join, and see appropriate details after acceptance.', 'Public viewers cannot access private details through pages, APIs, or exports.', 'Concurrent joins cannot exceed capacity or create duplicates.', 'Cancellation and material changes are visible to participants.']),
('Add discussion moderation and member privacy controls', 'M1 Community foundation', 'P0', [3, 4],
 'Keep a small local forum usable without relying on real-name verification or automated skill ratings.',
 ['Add the four initial discussion categories and replies with safe rendering.', 'Implement report, block, removal, suspension, and moderation audit records.', 'Define contribution terms, privacy notice, proposed age policy, deletion behavior, and log retention.', 'Add abuse limits for signup, login, posts, uploads, and expensive endpoints.', 'Assign moderation coverage and escalation for sensitive access reports.', 'Keep member content outside public dataset exports and model context.'],
 ['A moderator can handle a report and audit the action.', 'Blocking and visibility are enforced server-side.', 'Malicious HTML and oversized content are rejected or rendered safely.', 'The deletion and backup-retention behavior matches the published notice.']),
('Build and field-check the deterministic planner and map exports', 'M2 Reviewed session planner', 'P0', [2, 3],
 'Produce a useful warmup-to-project itinerary and PNG without any model call or paid map dependency.',
 ['Create area, feature, climb, source, access, and trail-graph models with review states.', 'Implement contextual name and alias resolution and discipline-specific grade ordering.', 'Filter closures and unsupported records before scoring candidate itineraries.', 'Respect a fixed project, editable time budget, walking preferences, and a return path.', 'Require reviewed trail edges for every navigable leg; fail usefully on disconnection.', 'Render an original SVG-to-PNG map or explicitly non-scale schematic with sources, dates, stop labels, and current-plan link.', 'Version saved plans and invalidate dependent caches when access or permission changes.', 'Have two local reviewers independently check paths and stop identification.'],
 ['Form-based planning works with no model credentials.', 'Every selected climb and trail edge belongs to the approved pack and meets hard constraints.', 'Closed or revoked records never appear as eligible stops.', 'Phone-readable exports match the saved plan and exclude unauthorized private details.', 'Field review resolves ambiguous junctions before navigable coverage is advertised.']),
('Add constrained conversational planning and hard spending limits', 'M3 Conversational pilot', 'P1', [6],
 'Allow natural-language preferences while preserving deterministic planning and predictable operating costs.',
 ['Define typed parsing and explanation schemas and a replaceable provider adapter.', 'Limit context to approved public catalog data and the necessary preferences.', 'Validate all model-returned identifiers and treat retrieved text as untrusted.', 'Add timeout, output, retry, per-user, and site-wide limits.', 'Reserve request budget atomically before provider calls and settle measured usage afterward.', 'Use revision-aware, privacy-scoped caching and fall back to structured planning.', 'Evaluate realistic requests, ambiguous names, prompt injection, invalid IDs, outages, and concurrent budget use.'],
 ['No known closure violations or fabricated IDs are accepted in the evaluation suite.', 'An exhausted budget or provider outage leaves core planning available.', 'Concurrent requests cannot exceed the configured reservation cap.', 'Private member messages and full profiles never enter model prompts.']),
('Run the local pilot and decide whether to expand', 'M3 Conversational pilot', 'P1', [4, 5, 6, 7],
 'Validate that people actually meet and climb together before adding many more crags.',
 ['Invite roughly 10 to 20 climbers and arrange several voluntarily hosted sessions.', 'Measure useful plans, accepted joins, self-reported completed outings, repeat use, and correction workload.', 'Check actual VPS latency, export readability, model spend, backups, and moderation response.', 'Review a four-week pilot against the documented goals and interview participants.', 'Resolve wrong-location, access, and privacy issues before public expansion.', 'Choose the next sector or area based on demand, permissions, field data, and maintenance ownership.', 'Create a separate rope-climbing requirements issue before implementing Leda or Foster Falls planning.'],
 ['Pilot findings and an explicit continue, revise, or pause decision are documented.', 'There are no unresolved material location, access, or privacy defects.', 'Every proposed new area has a source plan and maintenance owner.', 'Expansion is based on evidence rather than geographic coverage alone.'])
]
serialized = []
for i, (title, milestone, priority, deps, outcome, tasks, criteria) in enumerate(issues, 1):
    body = f'## Outcome\n\n{outcome}\n\n## Scope\n\n' + '\n'.join('- [ ] '+x for x in tasks)
    body += '\n\n## Acceptance criteria\n\n' + '\n'.join('- [ ] '+x for x in criteria)
    body += '\n\n## Dependencies\n\n' + (', '.join(f'Backlog E{x:02d}' for x in deps) if deps else 'Can start independently.')
    body += f'\n\nPriority: {priority}. Milestone: {milestone}.\n\nReference: [project plan](https://github.com/Dyno-man/Crag-Commune/blob/main/docs/planning/PROJECT_PLAN.md).\n'
    path = ROOT/'docs/issues'/f'E{i:02d}.md'
    path.write_text('# '+title+'\n\n'+body)
    serialized.append(dict(key=f'E{i:02d}',title=title,milestone=milestone,priority=priority,dependencies=deps,body=body,path=str(path.relative_to(ROOT))))
(ROOT/'docs/planning/issue-seed.json').write_text(json.dumps(serialized, indent=2)+'\n')
roadmap = '''# Roadmap and implementation backlog\n\nThis is a proposed sequence. Items are not implemented. Data permission and local review determine planner readiness; community development can proceed independently. See the full project plan for rationale.\n\n## Milestones\n\n| Milestone | Outcome | Exit condition |\n| --- | --- | --- |\n| M0 Data feasibility | A viable first area | Scope, permitted catalog, and review ownership confirmed |\n| M1 Community foundation | A small usable local community | Profiles, outings, discussion, privacy, moderation, and recovery work |\n| M2 Reviewed session planner | Form-based itinerary and original PNG | Approved data, tested constraints, and field-checked trails |\n| M3 Conversational pilot | Bounded chat and evidence from real use | Model controls work and pilot results support launch or revision |\n\n## Initial epics\n\n| ID | Epic | Priority | Dependencies |\n| --- | --- | --- | --- |\n'''
for item in serialized:
    dep=', '.join(f'E{x:02d}' for x in item['dependencies']) or 'None'
    roadmap += f"| {item['key']} | [{item['title']}](../issues/{item['key']}.md) | {item['priority']} | {dep} |\n"
roadmap += '''\nSplit each epic into focused implementation issues as it becomes ready. Checklists in docs/issues provide concrete work and acceptance criteria. issue-seed.json contains the initial issue bodies. Track ongoing status on GitHub rather than rewriting the original research document on every task completion.\n\n## Deferred work\n\n- Additional Stone Fort sectors, followed by areas with reviewed data and maintainers.\n- Rope-climbing planning with separate equipment and eligibility requirements.\n- Deeper conditions integration, subject to owner agreement.\n- Direct messages, notification email, and richer member controls based on pilot feedback.\n- Live GPS, native mobile apps, offline basemaps, and regional coverage only after demonstrated demand.\n\n## Estimate\n\nFor one experienced part-time developer, allow roughly 6 to 11 development weeks across the first four stages, plus the four-week pilot. These are planning estimates, not deadlines; licensing responses and local field review may take longer.\n'''
(ROOT/'docs/planning/ROADMAP.md').write_text(roadmap)
